screen:
  width: 1920
  height: 1080
bg_colour: "black"
outline_colour: "red"
distance: 200
zoom_step: 50
rotation_step: 3
step: 2
polygons:
  # closer right
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [1, 0, 2], [1, 1, 2], [1, 1, 1]]
  - [[2, 0, 1], [2, 0, 2], [2, 1, 2], [2, 1, 1]]
  - [[1, 0, 2], [2, 0, 2], [2, 1, 2], [1, 1, 2]]
  # closer left
  - [[-1, 0, 1], [-2, 0, 1], [-2, 1, 1], [-1, 1, 1]]
  - [[-1, 0, 1], [-1, 0, 2], [-1, 1, 2], [-1, 1, 1]]
  - [[-2, 0, 1], [-2, 0, 2], [-2, 1, 2], [-2, 1, 1]]
  - [[-1, 0, 2], [-2, 0, 2], [-2, 1, 2], [-1, 1, 2]]
  # further right
  - [[1, 0, 3], [2, 0, 3], [2, 1, 3], [1, 1, 3]]
  - [[1, 0, 3], [1, 0, 4], [1, 1, 4], [1, 1, 3]]
  - [[2, 0, 3], [2, 0, 4], [2, 1, 4], [2, 1, 3]]
  - [[1, 0, 4], [2, 0, 4], [2, 1, 4], [1, 1, 4]]
  # further left
  - [[-1, 0, 3], [-2, 0, 3], [-2, 1, 3], [-1, 1, 3]]
  - [[-1, 0, 3], [-1, 0, 4], [-1, 1, 4], [-1, 1, 3]]
  - [[-2, 0, 3], [-2, 0, 4], [-2, 1, 4], [-2, 1, 3]]
  - [[-1, 0, 4], [-2, 0, 4], [-2, 1, 4], [-1, 1, 4]]