screen:
  width: 1920
  height: 1080
bg_colour: "black"
outline_colour: "white"
distance: 200
polygons:
  # top left cube
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  # top right cube
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  # bottom left cube
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  # bottom right cube
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]
  - [[1, 0, 1], [2, 0, 1], [2, 1, 1], [1, 1, 1]]